import 'package:flutter/material.dart';
import 'package:aman_enterprises/core/theme/app_theme.dart';

class Product {
  final String id;
  final String name;
  final String description;
  final double price;
  final double? originalPrice;
  final String unit;
  final String category;
  final String? imageUrl;
  final IconData icon;
  final Color iconColor;
  final Color backgroundColor;
  final int discount;
  final bool isFavorite;
  final double rating;
  final int reviewCount;
  final bool inStock;
  final List<String> tags;
  final int? b2bMinQty;
  final double? b2bPrice;
  final bool isB2BAvailable;

  const Product({
    required this.id,
    required this.name,
    required this.description,
    required this.price,
    this.originalPrice,
    required this.unit,
    required this.category,
    this.imageUrl,
    required this.icon,
    required this.iconColor,
    required this.backgroundColor,
    this.discount = 0,
    this.isFavorite = false,
    this.rating = 4.5,
    this.reviewCount = 100,
    this.inStock = true,
    this.tags = const [],
    this.b2bMinQty,
    this.b2bPrice,
    this.isB2BAvailable = true,
  });

  factory Product.fromJson(Map<String, dynamic> json) {
    // Helper to safely parse numbers (handles both String and num)
    double? parseDouble(dynamic value) {
      if (value == null) return null;
      if (value is num) return value.toDouble();
      if (value is String) return double.tryParse(value);
      return null;
    }
    
    int? parseInt(dynamic value) {
      if (value == null) return null;
      if (value is num) return value.toInt();
      if (value is String) return int.tryParse(value);
      return null;
    }

    // Handle nested image object from backend
    String? imgUrl;
    if (json['image'] is Map) {
      imgUrl = json['image']['url'];
    } else {
      imgUrl = json['imageUrl'] ?? json['image'];
    }

    return Product(
      id: json['id']?.toString() ?? json['_id']?.toString() ?? '',
      name: json['name'] ?? json['productName'] ?? '',
      description: json['description'] ?? '',
      price: parseDouble(json['price']) ?? 0.0,
      originalPrice: parseDouble(json['originalPrice']),
      unit: json['unit'] ?? '1 Unit', 
      category: json['category'] ?? json['parentCategory'] ?? '',
      imageUrl: imgUrl,
      icon: Icons.shopping_bag_outlined, 
      iconColor: AppColors.primaryGreen, 
      backgroundColor: Colors.grey.shade50, 
      discount: parseInt(json['discount']) ?? 0,
      isFavorite: json['isFavorite'] ?? false,
      rating: parseDouble(json['rating']) ?? 0.0,
      reviewCount: parseInt(json['reviewCount']) ?? 0,
      inStock: json['inStock'] ?? (parseInt(json['stock']) ?? 0) > 0,
      tags: (json['tags'] as List?)?.map((e) => e.toString()).toList() ?? [],
      b2bMinQty: parseInt(json['b2bMinQty']),
      b2bPrice: parseDouble(json['b2bPrice']),
      isB2BAvailable: json['isB2BAvailable'] ?? true,
    );
  }

  static List<Product> sampleProducts = [
    // ===== VEGETABLES =====
    Product(
      id: '1',
      name: 'Fresh Tomatoes',
      description: 'Farm fresh organic tomatoes, perfect for salads and cooking. Rich in vitamins and antioxidants.',
      price: 40,
      originalPrice: 60,
      unit: '500g',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=400',
      icon: Icons.eco_rounded,
      iconColor: Colors.red,
      backgroundColor: const Color(0xFFFFEBEE),
      discount: 33,
      rating: 4.7,
      reviewCount: 234,
      tags: ['Organic', 'Fresh'],
    ),
    Product(
      id: '6',
      name: 'Fresh Spinach',
      description: 'Nutrient-rich fresh spinach leaves. Washed and ready to cook.',
      price: 30,
      unit: '250g',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
      icon: Icons.grass_rounded,
      iconColor: Colors.green.shade700,
      backgroundColor: const Color(0xFFE8F5E9),
      rating: 4.4,
      reviewCount: 123,
      tags: ['Organic', 'Fresh'],
    ),
    Product(
      id: '9',
      name: 'Fresh Carrots',
      description: 'Crunchy and sweet carrots. Perfect for salads, cooking, or juicing.',
      price: 35,
      originalPrice: 45,
      unit: '500g',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
      icon: Icons.eco_rounded,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF3E0),
      discount: 22,
      rating: 4.5,
      reviewCount: 189,
      tags: ['Fresh', 'Healthy'],
    ),
    Product(
      id: '10',
      name: 'Fresh Potatoes',
      description: 'Premium quality potatoes. Ideal for frying, baking, or mashing.',
      price: 45,
      unit: '1 kg',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1596450523905-59bc6002ee8b?w=400',
      icon: Icons.eco_rounded,
      iconColor: Colors.brown,
      backgroundColor: const Color(0xFFEFEBE9),
      rating: 4.6,
      reviewCount: 276,
      tags: ['Fresh'],
    ),
    Product(
      id: '11',
      name: 'Fresh Onions',
      description: 'Red onions with strong flavor. Essential for every kitchen.',
      price: 30,
      unit: '1 kg',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400',
      icon: Icons.eco_rounded,
      iconColor: Colors.purple,
      backgroundColor: const Color(0xFFF3E5F5),
      rating: 4.3,
      reviewCount: 145,
      tags: ['Fresh'],
    ),
    Product(
      id: '12',
      name: 'Broccoli',
      description: 'Fresh green broccoli florets. High in fiber and vitamins.',
      price: 60,
      originalPrice: 80,
      unit: '500g',
      category: 'Vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400',
      icon: Icons.eco_rounded,
      iconColor: Colors.green,
      backgroundColor: const Color(0xFFE8F5E9),
      discount: 25,
      rating: 4.6,
      reviewCount: 167,
      tags: ['Organic', 'Healthy'],
    ),
    
    // ===== FRUITS =====
    Product(
      id: '2',
      name: 'Green Apples',
      description: 'Crispy and juicy green apples. Perfect for snacking or making delicious apple pies.',
      price: 120,
      originalPrice: 150,
      unit: '1 kg',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400',
      icon: Icons.apple,
      iconColor: Colors.green,
      backgroundColor: const Color(0xFFE8F5E9),
      discount: 20,
      isFavorite: true,
      rating: 4.8,
      reviewCount: 456,
      tags: ['Premium', 'Imported'],
    ),
    Product(
      id: '13',
      name: 'Fresh Bananas',
      description: 'Ripe yellow bananas. Great source of potassium and energy.',
      price: 50,
      unit: '1 Dozen',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
      icon: Icons.apple,
      iconColor: Colors.yellow.shade700,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.7,
      reviewCount: 523,
      tags: ['Fresh', 'Energy'],
    ),
    Product(
      id: '14',
      name: 'Fresh Oranges',
      description: 'Juicy and sweet oranges. Rich in Vitamin C.',
      price: 80,
      originalPrice: 100,
      unit: '1 kg',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400',
      icon: Icons.apple,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF3E0),
      discount: 20,
      rating: 4.6,
      reviewCount: 312,
      tags: ['Fresh', 'Vitamin C'],
    ),
    Product(
      id: '15',
      name: 'Fresh Strawberries',
      description: 'Sweet and juicy strawberries. Perfect for desserts and smoothies.',
      price: 150,
      originalPrice: 200,
      unit: '250g',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      icon: Icons.apple,
      iconColor: Colors.red,
      backgroundColor: const Color(0xFFFFEBEE),
      discount: 25,
      rating: 4.9,
      reviewCount: 678,
      tags: ['Premium', 'Sweet'],
    ),
    Product(
      id: '16',
      name: 'Fresh Grapes',
      description: 'Seedless green grapes. Sweet and refreshing.',
      price: 90,
      unit: '500g',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400',
      icon: Icons.apple,
      iconColor: Colors.green.shade800,
      backgroundColor: const Color(0xFFE8F5E9),
      rating: 4.5,
      reviewCount: 234,
      tags: ['Seedless', 'Fresh'],
    ),
    Product(
      id: '26',
      name: 'Fresh Mangoes',
      description: 'Sweet and juicy Alphonso mangoes. The king of fruits.',
      price: 150,
      unit: '1 kg',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400',
      icon: Icons.apple,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF3E0),
      isFavorite: true,
      rating: 4.9,
      reviewCount: 890,
      tags: ['Seasonal', 'Sweet'],
    ),
    Product(
      id: '27',
      name: 'Watermelon',
      description: 'Refreshing and hydrating watermelon. Perfect for summer.',
      price: 60,
      originalPrice: 80,
      unit: '1 pc (3-4kg)',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1589123849767-f275727e025a?w=400',
      icon: Icons.apple,
      iconColor: Colors.green.shade700,
      backgroundColor: const Color(0xFFE8F5E9),
      rating: 4.5,
      reviewCount: 345,
      tags: ['Fresh', 'Hydrating'],
    ),
    Product(
      id: '28',
      name: 'Fresh Pineapple',
      description: 'Sweet and tangy fresh pineapple. Rich in Vitamin C.',
      price: 90,
      unit: '1 pc',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400',
      icon: Icons.apple,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.6,
      reviewCount: 231,
      tags: ['Tropical', 'Fresh'],
    ),
    Product(
      id: '29',
      name: 'Fresh Papaya',
      description: 'Ripe and sweet papaya. Great for digestion.',
      price: 50,
      unit: '1 pc (1kg)',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1517260739337-6799d2ad9e48?w=400',
      icon: Icons.apple,
      iconColor: Colors.orange.shade700,
      backgroundColor: const Color(0xFFFFF3E0),
      discount: 10,
      rating: 4.4,
      reviewCount: 156,
      tags: ['Healthy', 'Digestion'],
    ),
    Product(
      id: '30',
      name: 'Pomegranate',
      description: 'Fresh pomegranate with ruby red seeds. Antioxidant rich.',
      price: 140,
      originalPrice: 180,
      unit: '1 kg',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1615485925763-8676c12d3586?w=400',
      icon: Icons.apple,
      iconColor: Colors.red.shade800,
      backgroundColor: const Color(0xFFFFEBEE),
      rating: 4.7,
      reviewCount: 423,
      tags: ['Antioxidant', 'Fresh'],
    ),
    Product(
      id: '31',
      name: 'Kiwi',
      description: 'Tangy and sweet kiwis. High in Vitamin C and fiber.',
      price: 180,
      unit: '3 pcs',
      category: 'Fruits',
      imageUrl: 'https://images.unsplash.com/photo-1518165388047-9759d5718a24?w=400',
      icon: Icons.apple,
      iconColor: Colors.green,
      backgroundColor: const Color(0xFFE8F5E9),
      rating: 4.6,
      reviewCount: 267,
      tags: ['Imported', 'Healthy'],
    ),
    
    // ===== DAIRY =====
    Product(
      id: '3',
      name: 'Fresh Milk',
      description: 'Pure and fresh cow milk. Pasteurized and packed with essential nutrients.',
      price: 65,
      unit: '1 Litre',
      category: 'Dairy',
      imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
      icon: Icons.local_drink_rounded,
      iconColor: Colors.blue,
      backgroundColor: const Color(0xFFE3F2FD),
      rating: 4.9,
      reviewCount: 789,
      tags: ['Fresh', 'Organic'],
    ),
    Product(
      id: '7',
      name: 'Greek Yogurt',
      description: 'Creamy Greek yogurt made from fresh milk. High in protein and probiotics.',
      price: 85,
      originalPrice: 100,
      unit: '400g',
      category: 'Dairy',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
      icon: Icons.icecream_rounded,
      iconColor: Colors.purple,
      backgroundColor: const Color(0xFFF3E5F5),
      discount: 15,
      rating: 4.7,
      reviewCount: 234,
      tags: ['Healthy', 'Protein'],
    ),
    Product(
      id: '17',
      name: 'Fresh Paneer',
      description: 'Soft and fresh cottage cheese. Perfect for curries and snacks.',
      price: 120,
      unit: '200g',
      category: 'Dairy',
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
      icon: Icons.local_drink_rounded,
      iconColor: Colors.white,
      backgroundColor: const Color(0xFFFFFDE7),
      rating: 4.8,
      reviewCount: 345,
      tags: ['Fresh', 'Protein'],
    ),
    Product(
      id: '18',
      name: 'Butter',
      description: 'Fresh and creamy butter. Made from pure cream.',
      price: 55,
      unit: '100g',
      category: 'Dairy',
      imageUrl: 'https://images.unsplash.com/photo-1589985270958-bf087e31adc6?w=400',
      icon: Icons.local_drink_rounded,
      iconColor: Colors.yellow.shade700,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.6,
      reviewCount: 267,
      tags: ['Fresh', 'Creamy'],
    ),
    Product(
      id: '19',
      name: 'Farm Eggs',
      description: 'Fresh farm eggs. Rich in protein and nutrients.',
      price: 80,
      unit: '12 pcs',
      category: 'Dairy',
      imageUrl: 'https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?w=400',
      icon: Icons.egg_rounded,
      iconColor: Colors.brown.shade300,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.7,
      reviewCount: 456,
      tags: ['Farm Fresh', 'Protein'],
    ),
    
    // ===== BAKERY =====
    Product(
      id: '4',
      name: 'Whole Wheat Bread',
      description: 'Freshly baked whole wheat bread. Soft, healthy, and perfect for sandwiches.',
      price: 45,
      unit: '400g',
      category: 'Bakery',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
      icon: Icons.breakfast_dining_rounded,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF3E0),
      rating: 4.6,
      reviewCount: 321,
      tags: ['Fresh', 'Healthy'],
    ),
    Product(
      id: '20',
      name: 'Croissants',
      description: 'Buttery and flaky French croissants. Perfect for breakfast.',
      price: 60,
      originalPrice: 80,
      unit: '2 pcs',
      category: 'Bakery',
      imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400',
      icon: Icons.breakfast_dining_rounded,
      iconColor: Colors.brown,
      backgroundColor: const Color(0xFFFFF3E0),
      discount: 25,
      rating: 4.8,
      reviewCount: 198,
      tags: ['Fresh', 'Imported'],
    ),
    Product(
      id: '21',
      name: 'Chocolate Cake',
      description: 'Rich chocolate cake slice. Decadent and delicious.',
      price: 150,
      unit: '1 Slice',
      category: 'Bakery',
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
      icon: Icons.cake_rounded,
      iconColor: Colors.brown.shade800,
      backgroundColor: const Color(0xFFEFEBE9),
      rating: 4.9,
      reviewCount: 567,
      tags: ['Premium', 'Sweet'],
    ),
    
    // ===== GRAINS =====
    Product(
      id: '5',
      name: 'Basmati Rice',
      description: 'Premium aged basmati rice. Long grain, aromatic, and perfect for biryani.',
      price: 180,
      originalPrice: 220,
      unit: '1 kg',
      category: 'Grains',
      imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
      icon: Icons.rice_bowl_rounded,
      iconColor: Colors.brown,
      backgroundColor: const Color(0xFFEFEBE9),
      discount: 18,
      rating: 4.5,
      reviewCount: 567,
      tags: ['Premium', 'Aged'],
    ),
    Product(
      id: '22',
      name: 'Wheat Flour',
      description: 'Whole wheat flour for chapatis and parathas.',
      price: 60,
      unit: '1 kg',
      category: 'Grains',
      imageUrl: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=400',
      icon: Icons.rice_bowl_rounded,
      iconColor: Colors.brown.shade300,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.4,
      reviewCount: 234,
      tags: ['Whole Grain'],
    ),
    Product(
      id: '23',
      name: 'Oats',
      description: 'Rolled oats for healthy breakfast. High in fiber.',
      price: 120,
      originalPrice: 150,
      unit: '500g',
      category: 'Grains',
      imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400',
      icon: Icons.rice_bowl_rounded,
      iconColor: Colors.brown.shade200,
      backgroundColor: const Color(0xFFFFF8E1),
      discount: 20,
      rating: 4.7,
      reviewCount: 345,
      tags: ['Healthy', 'Fiber'],
    ),
    
    // ===== BEVERAGES =====
    Product(
      id: '8',
      name: 'Orange Juice',
      description: '100% pure orange juice with no added sugar. Fresh and refreshing.',
      price: 95,
      unit: '1 Litre',
      category: 'Beverages',
      imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
      icon: Icons.local_cafe_rounded,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.6,
      reviewCount: 345,
      tags: ['Fresh', 'No Sugar'],
    ),
    Product(
      id: '24',
      name: 'Green Tea',
      description: 'Premium green tea leaves. Antioxidant rich and refreshing.',
      price: 150,
      unit: '100g',
      category: 'Beverages',
      imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400',
      icon: Icons.local_cafe_rounded,
      iconColor: Colors.green,
      backgroundColor: const Color(0xFFE8F5E9),
      rating: 4.8,
      reviewCount: 289,
      tags: ['Organic', 'Healthy'],
    ),
    Product(
      id: '25',
      name: 'Cold Coffee',
      description: 'Ready to drink cold coffee. Creamy and refreshing.',
      price: 50,
      originalPrice: 65,
      unit: '200ml',
      category: 'Beverages',
      imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400',
      icon: Icons.local_cafe_rounded,
      iconColor: Colors.brown,
      backgroundColor: const Color(0xFFEFEBE9),
      discount: 23,
      rating: 4.5,
      reviewCount: 412,
      tags: ['Ready to Drink'],
    ),
    // ===== MEAT & FISH =====
    Product(
      id: '32',
      name: 'Fresh Chicken Breast',
      description: 'Boneless and skinless chicken breast. High protein.',
      price: 220,
      unit: '500g',
      category: 'Meat & Fish',
      imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400',
      icon: Icons.set_meal_rounded,
      iconColor: Colors.red.shade400,
      backgroundColor: const Color(0xFFFFEBEE),
      rating: 4.8,
      reviewCount: 345,
      tags: ['Fresh', 'Protein'],
    ),
    Product(
      id: '33',
      name: 'Salmon Fillet',
      description: 'Premium Atlantic salmon fillet. Rich in Omega-3.',
      price: 550,
      originalPrice: 700,
      unit: '250g',
      category: 'Meat & Fish',
      imageUrl: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=400',
      icon: Icons.set_meal_rounded,
      iconColor: Colors.red.shade300,
      backgroundColor: const Color(0xFFFFEBEE),
      discount: 21,
      rating: 4.9,
      reviewCount: 123,
      tags: ['Premium', 'Healthy'],
    ),
    Product(
      id: '34',
      name: 'Fresh Mutton',
      description: 'Tender and fresh mutton curry cut.',
      price: 600,
      unit: '500g',
      category: 'Meat & Fish',
      imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6f54262?w=400',
      icon: Icons.set_meal_rounded,
      iconColor: Colors.brown,
      backgroundColor: const Color(0xFFEFEBE9),
      rating: 4.7,
      reviewCount: 234,
      tags: ['Fresh'],
    ),

    // ===== SNACKS =====
    Product(
      id: '35',
      name: 'Potato Chips (Salted)',
      description: 'Crispy salted potato chips. Perfect party snack.',
      price: 20,
      unit: '50g',
      category: 'Snacks',
      imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
      icon: Icons.fastfood_rounded,
      iconColor: Colors.amber,
      backgroundColor: const Color(0xFFFFF8E1),
      rating: 4.5,
      reviewCount: 567,
      tags: ['Crispy'],
    ),
    Product(
      id: '36',
      name: 'Chocolate Chip Cookies',
      description: 'Crunchy chocolate chip cookies.',
      price: 40,
      unit: '100g',
      category: 'Snacks',
      imageUrl: 'https://images.unsplash.com/photo-1499636138143-bd63e7318808?w=400',
      icon: Icons.cookie_rounded,
      iconColor: Colors.brown,
      backgroundColor: const Color(0xFFEFEBE9),
      rating: 4.8,
      reviewCount: 456,
      tags: ['Sweet'],
    ),
    Product(
      id: '37',
      name: 'Dark Chocolate',
      description: 'Rich dark chocolate bar. 70% Cocoa.',
      price: 150,
      unit: '1 Bar',
      category: 'Snacks',
      imageUrl: 'https://images.unsplash.com/photo-1511381978029-1a3b9347c430?w=400',
      icon: Icons.cookie_rounded,
      iconColor: Colors.brown.shade800,
      backgroundColor: const Color(0xFFD7CCC8),
      rating: 4.9,
      reviewCount: 789,
      tags: ['Premium', 'Sweet'],
    ),
    Product(
      id: '38',
      name: 'Butter Popcorn',
      description: 'Movie style butter popcorn.',
      price: 30,
      unit: '1 Packet',
      category: 'Snacks',
      imageUrl: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=400',
      icon: Icons.fastfood_rounded,
      iconColor: Colors.yellow.shade800,
      backgroundColor: const Color(0xFFFFF3E0),
      rating: 4.6,
      reviewCount: 345,
      tags: ['Tasty'],
    ),

    // ===== FROZEN FOODS =====
    Product(
      id: '39',
      name: 'French Fries',
      description: 'Ready to fry frozen french fries.',
      price: 150,
      unit: '500g',
      category: 'Frozen Foods',
      imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400',
      icon: Icons.ac_unit_rounded,
      iconColor: Colors.lightBlue,
      backgroundColor: const Color(0xFFE3F2FD),
      rating: 4.7,
      reviewCount: 432,
      tags: ['Frozen', 'Convenient'],
    ),
    Product(
      id: '40',
      name: 'Frozen Peas',
      description: 'Sweet and tender frozen green peas.',
      price: 80,
      unit: '500g',
      category: 'Frozen Foods',
      imageUrl: 'https://images.unsplash.com/photo-1592394533824-946a48d88e7a?w=400',
      icon: Icons.ac_unit_rounded,
      iconColor: Colors.green,
      backgroundColor: const Color(0xFFE8F5E9),
      rating: 4.5,
      reviewCount: 231,
      tags: ['Frozen'],
    ),
    Product(
      id: '41',
      name: 'Chicken Nuggets',
      description: 'Crispy frozen chicken nuggets.',
      price: 250,
      unit: '400g',
      category: 'Frozen Foods',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      icon: Icons.ac_unit_rounded,
      iconColor: Colors.orange,
      backgroundColor: const Color(0xFFFFF3E0),
      rating: 4.6,
      reviewCount: 345,
      tags: ['Frozen', 'Snack'],
    ),

    // ===== CLEANING =====
    Product(
      id: '42',
      name: 'Laundry Detergent',
      description: 'Liquid laundry detergent for tough stains.',
      price: 250,
      unit: '1 Litre',
      category: 'Cleaning',
      imageUrl: 'https://images.unsplash.com/photo-1582650893348-18eebdb12c42?w=400',
      icon: Icons.cleaning_services_rounded,
      iconColor: Colors.blueAccent,
      backgroundColor: const Color(0xFFE3F2FD),
      rating: 4.8,
      reviewCount: 567,
      tags: ['Essentials'],
    ),
    Product(
      id: '43',
      name: 'Dishwashing Liquid',
      description: 'Lemon scented dishwashing liquid.',
      price: 100,
      unit: '500ml',
      category: 'Cleaning',
      imageUrl: 'https://images.unsplash.com/photo-1585834892288-5c4d3753716d?w=400',
      icon: Icons.cleaning_services_rounded,
      iconColor: Colors.yellow,
      backgroundColor: const Color(0xFFFFFDE7),
      rating: 4.7,
      reviewCount: 678,
      tags: ['Essentials'],
    ),

    // ===== PERSONAL CARE =====
    Product(
      id: '44',
      name: 'Shampoo',
      description: 'Herbal shampoo for strong and healthy hair.',
      price: 180,
      unit: '200ml',
      category: 'Personal Care',
      imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400',
      icon: Icons.spa_rounded,
      iconColor: Colors.pink.shade300,
      backgroundColor: const Color(0xFFFCE4EC),
      rating: 4.6,
      reviewCount: 456,
      tags: ['Hair Care'],
    ),
    Product(
      id: '45',
      name: 'Handmade Soap',
      description: 'Natural handmade soap with lavender.',
      price: 120,
      unit: '1 Bar',
      category: 'Personal Care',
      imageUrl: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f214?w=400',
      icon: Icons.spa_rounded,
      iconColor: Colors.purple.shade300,
      backgroundColor: const Color(0xFFF3E5F5),
      rating: 4.8,
      reviewCount: 234,
      tags: ['Natural'],
    ),

    // ===== BABY CARE =====
    Product(
      id: '46',
      name: 'Baby Lotion',
      description: 'Gentle moisturizing lotion for baby skin.',
      price: 250,
      unit: '200ml',
      category: 'Baby Care',
      imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
      icon: Icons.child_care_rounded,
      iconColor: Colors.blue.shade300,
      backgroundColor: const Color(0xFFE3F2FD),
      rating: 4.9,
      reviewCount: 123,
      tags: ['Gentle', 'Safe'],
    ),
    Product(
      id: '47',
      name: 'Baby Wipes',
      description: 'Soft and gentle baby wipes.',
      price: 150,
      unit: '72 pcs',
      category: 'Baby Care',
      imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400',
      icon: Icons.child_care_rounded,
      iconColor: Colors.teal.shade300,
      backgroundColor: const Color(0xFFE0F2F1),
      rating: 4.8,
      reviewCount: 345,
      tags: ['Essentials'],
    ),
    // ===== VEGETABLES (Adding 5 more to reach >10) =====
    Product(id: '48', name: 'Cucumber', description: 'Fresh green cucumber.', price: 20, unit: '500g', category: 'Vegetables', imageUrl: 'assets/images/products/cucumber.jpg', icon: Icons.eco_rounded, iconColor: Colors.green, backgroundColor: const Color(0xFFE8F5E9)),
    Product(id: '49', name: 'Capsicum', description: 'Fresh green capsicum.', price: 40, unit: '250g', category: 'Vegetables', imageUrl: 'assets/images/products/capsicum.jpg', icon: Icons.eco_rounded, iconColor: Colors.green, backgroundColor: const Color(0xFFE8F5E9)),
    Product(id: '50', name: 'Ginger', description: 'Fresh ginger root.', price: 30, unit: '100g', category: 'Vegetables', imageUrl: 'assets/images/products/ginger.jpg', icon: Icons.eco_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '51', name: 'Garlic', description: 'Fresh garlic bulbs.', price: 20, unit: '100g', category: 'Vegetables', imageUrl: 'assets/images/products/garlic.jpg', icon: Icons.eco_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFF5F5F5)),
    Product(id: '52', name: 'Cauliflower', description: 'Whole fresh cauliflower.', price: 45, unit: '1 pc', category: 'Vegetables', imageUrl: 'assets/images/products/cauliflower.jpg', icon: Icons.eco_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFF5F5F5)),

    // ===== DAIRY (Adding 5 more) =====
    Product(id: '53', name: 'Cheese Slices', description: 'Processed cheese slices.', price: 120, unit: '10 slices', category: 'Dairy', imageUrl: 'assets/images/products/cheese_slices.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
    Product(id: '54', name: 'Salted Butter', description: 'Table salted butter.', price: 58, unit: '100g', category: 'Dairy', imageUrl: 'assets/images/products/salted_butter.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFF8E1)),
    Product(id: '55', name: 'Fresh Cream', description: 'Rich fresh cream.', price: 80, unit: '200ml', category: 'Dairy', imageUrl: 'assets/images/products/fresh_cream.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFFAFAFA)),
    Product(id: '56', name: 'Flavoured Milk', description: 'Strawberry flavoured milk.', price: 30, unit: '200ml', category: 'Dairy', imageUrl: 'assets/images/products/flavoured_milk.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '57', name: 'Condensed Milk', description: 'Sweetened condensed milk.', price: 110, unit: '400g', category: 'Dairy', imageUrl: 'assets/images/products/condensed_milk.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.amber, backgroundColor: const Color(0xFFFFF8E1)),

    // ===== BAKERY (Adding 7 more) =====
    Product(id: '58', name: 'Burger Buns', description: 'Soft burger buns.', price: 40, unit: '4 pcs', category: 'Bakery', imageUrl: 'assets/images/products/burger_buns.jpg', icon: Icons.breakfast_dining_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '59', name: 'Pizza Base', description: 'Readymade pizza base.', price: 35, unit: '2 pcs', category: 'Bakery', imageUrl: 'assets/images/products/pizza_base.jpg', icon: Icons.local_pizza_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '60', name: 'Cupcakes', description: 'Vanilla cupcakes.', price: 80, unit: '4 pcs', category: 'Bakery', imageUrl: 'assets/images/products/cupcakes.jpg', icon: Icons.cake_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '61', name: 'Rusks', description: 'Crunchy tea rusks.', price: 50, unit: '200g', category: 'Bakery', imageUrl: 'assets/images/products/rusks.jpg', icon: Icons.breakfast_dining_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '62', name: 'Chocolate Muffin', description: 'Rich chocolate muffin.', price: 40, unit: '1 pc', category: 'Bakery', imageUrl: 'assets/images/products/chocolate_muffin.jpg', icon: Icons.cake_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFD7CCC8)),
    Product(id: '63', name: 'Garlic Bread', description: 'Fresh garlic bread.', price: 60, unit: '1 pc', category: 'Bakery', imageUrl: 'assets/images/products/garlic_bread.jpg', icon: Icons.breakfast_dining_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '64', name: 'Bagel', description: 'Fresh bagel.', price: 30, unit: '1 pc', category: 'Bakery', imageUrl: 'assets/images/products/bagel.jpg', icon: Icons.breakfast_dining_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),

    // ===== GRAINS (Adding 7 more) =====
    Product(id: '65', name: 'Toor Dal', description: 'Premium Toor Dal.', price: 130, unit: '1 kg', category: 'Grains', imageUrl: 'assets/images/products/toor_dal.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
    Product(id: '66', name: 'Moong Dal', description: 'Yellow Moong Dal.', price: 110, unit: '1 kg', category: 'Grains', imageUrl: 'assets/images/products/moong_dal.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
    Product(id: '67', name: 'Chana Dal', description: 'Split Bengal gram.', price: 90, unit: '1 kg', category: 'Grains', imageUrl: 'assets/images/products/chana_dal.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '68', name: 'Urad Dal', description: 'Whole white Urad dal.', price: 140, unit: '1 kg', category: 'Grains', imageUrl: 'assets/images/products/urad_dal.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFF5F5F5)),
    Product(id: '69', name: 'Masoor Dal', description: 'Red Lentils.', price: 100, unit: '1 kg', category: 'Grains', imageUrl: 'assets/images/products/masoor_dal.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),
    Product(id: '70', name: 'Soya Chunks', description: 'High protein soya chunks.', price: 50, unit: '200g', category: 'Grains', imageUrl: 'assets/images/products/soya_chunks.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '71', name: 'Rajma', description: 'Red kidney beans.', price: 120, unit: '1 kg', category: 'Grains', imageUrl: 'assets/images/products/rajma.jpg', icon: Icons.rice_bowl_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),

    // ===== BEVERAGES (Adding 7 more) =====
    Product(id: '72', name: 'Mineral Water', description: '1L Water Bottle.', price: 20, unit: '1 L', category: 'Beverages', imageUrl: 'assets/images/products/mineral_water.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '73', name: 'Soda Water', description: 'Carbonated soda water.', price: 15, unit: '500ml', category: 'Beverages', imageUrl: 'assets/images/products/soda_water.jpg', icon: Icons.local_bar_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFF5F5F5)),
    Product(id: '74', name: 'Energy Drink', description: 'Caffeinated energy drink.', price: 110, unit: '250ml', category: 'Beverages', imageUrl: 'assets/images/products/energy_drink.jpg', icon: Icons.bolt_rounded, iconColor: Colors.amber, backgroundColor: const Color(0xFFFFF8E1)),
    Product(id: '75', name: 'Apple Juice', description: 'Fresh apple juice.', price: 100, unit: '1 L', category: 'Beverages', imageUrl: 'assets/images/products/apple_juice.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),
    Product(id: '76', name: 'Tea Bags', description: 'Premium Assam Tea Bags.', price: 150, unit: '50 pcs', category: 'Beverages', imageUrl: 'assets/images/products/tea_bags.jpg', icon: Icons.local_cafe_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '77', name: 'Coffee Powder', description: 'Instant coffee powder.', price: 180, unit: '50g', category: 'Beverages', imageUrl: 'assets/images/products/coffee_powder.jpg', icon: Icons.local_cafe_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '78', name: 'Lemonade', description: 'Fresh lemonade.', price: 40, unit: '500ml', category: 'Beverages', imageUrl: 'assets/images/products/lemonade.jpg', icon: Icons.local_drink_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),

    // ===== MEAT & FISH (Adding 7 more) =====
    Product(id: '79', name: 'Prawns', description: 'Fresh cleaned prawns.', price: 450, unit: '250g', category: 'Meat & Fish', imageUrl: 'assets/images/products/prawns.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '80', name: 'Fish Steaks', description: 'Seer fish steaks.', price: 700, unit: '500g', category: 'Meat & Fish', imageUrl: 'assets/images/products/fish_steaks.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),
    Product(id: '81', name: 'Chicken Curry Cut', description: 'Skinless chicken curry cut.', price: 180, unit: '500g', category: 'Meat & Fish', imageUrl: 'assets/images/products/chicken_curry_cut.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),
    Product(id: '82', name: 'Chicken Wings', description: 'Fresh chicken wings.', price: 150, unit: '500g', category: 'Meat & Fish', imageUrl: 'assets/images/products/chicken_wings.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '83', name: 'Lamb Chops', description: 'Fresh lamb chops.', price: 850, unit: '500g', category: 'Meat & Fish', imageUrl: 'assets/images/products/lamb_chops.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),
    Product(id: '84', name: 'Pork Chops', description: 'Pork chops.', price: 600, unit: '500g', category: 'Meat & Fish', imageUrl: 'assets/images/products/pork_chops.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '85', name: 'Crab', description: 'Fresh sea crab.', price: 500, unit: '1 kg', category: 'Meat & Fish', imageUrl: 'assets/images/products/crab.jpg', icon: Icons.set_meal_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),

    // ===== SNACKS (Adding 6 more) =====
    Product(id: '86', name: 'Namkeen Mix', description: 'Spicy snack mix.', price: 50, unit: '200g', category: 'Snacks', imageUrl: 'assets/images/products/namkeen.jpg', icon: Icons.fastfood_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '87', name: 'Bhujia', description: 'Crispy bhujia sev.', price: 40, unit: '200g', category: 'Snacks', imageUrl: 'assets/images/products/bhujia.jpg', icon: Icons.fastfood_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
    Product(id: '88', name: 'Digestive Biscuits', description: 'Healthy digestive biscuits.', price: 30, unit: '100g', category: 'Snacks', imageUrl: 'assets/images/products/digestive_biscuits.jpg', icon: Icons.cookie_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '89', name: 'Cream Biscuits', description: 'Chocolate cream biscuits.', price: 20, unit: '1 pack', category: 'Snacks', imageUrl: 'assets/images/products/cream_biscuits.jpg', icon: Icons.cookie_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),
    Product(id: '90', name: 'Nachos', description: 'Cheese nachos chips.', price: 60, unit: '150g', category: 'Snacks', imageUrl: 'assets/images/products/nachos.jpg', icon: Icons.fastfood_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '91', name: 'Salted Peanuts', description: 'Roasted salted peanuts.', price: 20, unit: '100g', category: 'Snacks', imageUrl: 'assets/images/products/peanuts.jpg', icon: Icons.fastfood_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),

    // ===== FROZEN FOODS (Adding 7 more) =====
    Product(id: '92', name: 'Frozen Corn', description: 'Sweet frozen corn kernels.', price: 90, unit: '500g', category: 'Frozen Foods', imageUrl: 'assets/images/products/frozen_corn.jpg', icon: Icons.ac_unit_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
    Product(id: '93', name: 'Frozen Pizza', description: 'Margherita frozen pizza.', price: 200, unit: '1 pc', category: 'Frozen Foods', imageUrl: 'assets/images/products/frozen_pizza.jpg', icon: Icons.local_pizza_rounded, iconColor: Colors.red, backgroundColor: const Color(0xFFFFEBEE)),
    Product(id: '94', name: 'Frozen Momos', description: 'Veg frozen momos.', price: 120, unit: '10 pcs', category: 'Frozen Foods', imageUrl: 'assets/images/products/frozen_momos.jpg', icon: Icons.ac_unit_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFF5F5F5)),
    Product(id: '95', name: 'Vanilla Ice Cream', description: 'Family pack vanilla ice cream.', price: 180, unit: '700ml', category: 'Frozen Foods', imageUrl: 'assets/images/products/vanilla_icecream.jpg', icon: Icons.icecream_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '96', name: 'Popsicles', description: 'Fruit popsicles.', price: 20, unit: '1 pc', category: 'Frozen Foods', imageUrl: 'assets/images/products/popsicles.jpg', icon: Icons.icecream_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '97', name: 'Mixed Berries', description: 'Frozen mixed berries.', price: 300, unit: '250g', category: 'Frozen Foods', imageUrl: 'assets/images/products/mixed_berries.jpg', icon: Icons.ac_unit_rounded, iconColor: Colors.purple, backgroundColor: const Color(0xFFF3E5F5)),
    Product(id: '98', name: 'Hash Browns', description: 'Frozen potato hash browns.', price: 110, unit: '10 pcs', category: 'Frozen Foods', imageUrl: 'assets/images/products/hash_browns.jpg', icon: Icons.fastfood_rounded, iconColor: Colors.brown, backgroundColor: const Color(0xFFEFEBE9)),

    // ===== CLEANING (Adding 8 more) =====
    Product(id: '99', name: 'Floor Cleaner', description: 'Disinfectant floor cleaner.', price: 150, unit: '1 L', category: 'Cleaning', imageUrl: 'assets/images/products/floor_cleaner.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '100', name: 'Toilet Cleaner', description: 'Powerful toilet cleaner.', price: 90, unit: '500ml', category: 'Cleaning', imageUrl: 'assets/images/products/toilet_cleaner.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '101', name: 'Glass Cleaner', description: 'Spray glass cleaner.', price: 80, unit: '500ml', category: 'Cleaning', imageUrl: 'assets/images/products/glass_cleaner.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '102', name: 'Sponge Wipes', description: 'Kitchen sponge wipes.', price: 40, unit: '3 pcs', category: 'Cleaning', imageUrl: 'assets/images/products/sponge_wipes.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
    Product(id: '103', name: 'Garbage Bags', description: 'Medium size garbage bags.', price: 60, unit: '30 pcs', category: 'Cleaning', imageUrl: 'assets/images/products/garbage_bags.jpg', icon: Icons.delete_outline_rounded, iconColor: Colors.black, backgroundColor: const Color(0xFFFAFAFA)),
    Product(id: '104', name: 'Air Freshener', description: 'Lavender air freshener spray.', price: 140, unit: '200ml', category: 'Cleaning', imageUrl: 'assets/images/products/air_freshener.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.purple, backgroundColor: const Color(0xFFF3E5F5)),
    Product(id: '105', name: 'Dish Bar', description: 'Dish wash bar.', price: 20, unit: '200g', category: 'Cleaning', imageUrl: 'assets/images/products/dish_bar.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.green, backgroundColor: const Color(0xFFE8F5E9)),
    Product(id: '106', name: 'Mop', description: 'Floor cleaning mop.', price: 300, unit: '1 pc', category: 'Cleaning', imageUrl: 'assets/images/products/mop.jpg', icon: Icons.cleaning_services_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),

    // ===== PERSONAL CARE (Adding 8 more) =====
    Product(id: '107', name: 'Toothpaste', description: 'Herbal toothpaste.', price: 90, unit: '150g', category: 'Personal Care', imageUrl: 'assets/images/products/toothpaste.jpg', icon: Icons.spa_rounded, iconColor: Colors.green, backgroundColor: const Color(0xFFE8F5E9)),
    Product(id: '108', name: 'Toothbrush', description: 'Soft bristle toothbrush.', price: 30, unit: '1 pc', category: 'Personal Care', imageUrl: 'assets/images/products/toothbrush.jpg', icon: Icons.spa_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '109', name: 'Body Wash', description: 'Shower gel body wash.', price: 180, unit: '250ml', category: 'Personal Care', imageUrl: 'assets/images/products/body_wash.jpg', icon: Icons.spa_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '110', name: 'Face Wash', description: 'Neem face wash.', price: 120, unit: '100ml', category: 'Personal Care', imageUrl: 'assets/images/products/face_wash.jpg', icon: Icons.spa_rounded, iconColor: Colors.green, backgroundColor: const Color(0xFFE8F5E9)),
    Product(id: '111', name: 'Deodorant', description: 'Body spray deodorant.', price: 190, unit: '150ml', category: 'Personal Care', imageUrl: 'assets/images/products/deodorant.jpg', icon: Icons.spa_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '112', name: 'Razor', description: 'Disposable razor.', price: 40, unit: '1 pc', category: 'Personal Care', imageUrl: 'assets/images/products/razor.jpg', icon: Icons.check_rounded, iconColor: Colors.grey, backgroundColor: const Color(0xFFF5F5F5)),
    Product(id: '113', name: 'Hair Oil', description: 'Coconut hair oil.', price: 100, unit: '200ml', category: 'Personal Care', imageUrl: 'assets/images/products/hair_oil.jpg', icon: Icons.spa_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '114', name: 'Conditioner', description: 'Smooth hair conditioner.', price: 190, unit: '180ml', category: 'Personal Care', imageUrl: 'assets/images/products/conditioner.jpg', icon: Icons.spa_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),

    // ===== BABY CARE (Adding 7 more) =====
    Product(id: '115', name: 'Diapers (S)', description: 'Baby diapers Small size.', price: 800, unit: '60 pcs', category: 'Baby Care', imageUrl: 'assets/images/products/diapers_s.jpg', icon: Icons.child_care_rounded, iconColor: Colors.purple, backgroundColor: const Color(0xFFF3E5F5)),
    Product(id: '116', name: 'Diapers (M)', description: 'Baby diapers Medium size.', price: 900, unit: '60 pcs', category: 'Baby Care', imageUrl: 'assets/images/products/diapers_s.jpg', icon: Icons.child_care_rounded, iconColor: Colors.purple, backgroundColor: const Color(0xFFF3E5F5)),
    Product(id: '117', name: 'Baby Powder', description: 'Soft baby talcum powder.', price: 90, unit: '200g', category: 'Baby Care', imageUrl: 'assets/images/products/baby_powder.jpg', icon: Icons.child_care_rounded, iconColor: Colors.pink, backgroundColor: const Color(0xFFFCE4EC)),
    Product(id: '118', name: 'Baby Oil', description: 'Massage oil for babies.', price: 150, unit: '100ml', category: 'Baby Care', imageUrl: 'assets/images/products/baby_oil.jpg', icon: Icons.child_care_rounded, iconColor: Colors.orange, backgroundColor: const Color(0xFFFFF3E0)),
    Product(id: '119', name: 'Baby Soap', description: 'Mild baby soap bar.', price: 50, unit: '75g', category: 'Baby Care', imageUrl: 'assets/images/products/baby_soap.jpg', icon: Icons.child_care_rounded, iconColor: Colors.white, backgroundColor: const Color(0xFFF5F5F5)),
    Product(id: '120', name: 'Feeding Bottle', description: 'BPA free feeding bottle.', price: 250, unit: '250ml', category: 'Baby Care', imageUrl: 'assets/images/products/feeding_bottle.jpg', icon: Icons.child_care_rounded, iconColor: Colors.blue, backgroundColor: const Color(0xFFE3F2FD)),
    Product(id: '121', name: 'Baby Food', description: 'Cerelac baby food.', price: 300, unit: '400g', category: 'Baby Care', imageUrl: 'assets/images/products/baby_food.jpg', icon: Icons.child_care_rounded, iconColor: Colors.green, backgroundColor: const Color(0xFFE8F5E9)),
    Product(id: '122', name: 'Baby Shampoo', description: 'No-tears baby shampoo.', price: 200, unit: '100ml', category: 'Baby Care', imageUrl: 'assets/images/products/baby_shampoo.jpg', icon: Icons.child_care_rounded, iconColor: Colors.yellow, backgroundColor: const Color(0xFFFFFDE7)),
  ];
}
